---
  - include_vars: main.yml

  - name: Install libnss-ldapd package
    apt: name=libnss-ldapd state=latest force=yes update_cache=yes cache_valid_time={{ apt_cache_time | default(300) }}
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Install nss-pam-ldapd port.
    portinstall: name=nss-pam-ldapd state=present
    when: ansible_distribution == 'FreeBSD'

  - name: Install pam_mkhomedir port.
    portinstall: name=pam_mkhomedir state=present
    when: ansible_distribution == 'FreeBSD'

  - name: Copying config file
    template: src=templates/nslcd.conf.j2 dest={{ nslcd_conf_dir }}/nslcd.conf owner=root mode=600
    notify:
      - nslcd restart
      - nscd restart

  - name: Change /etc/nsswitch.conf file
    copy: src=files/nsswitch.conf dest=/etc/nsswitch.conf owner=root mode=644
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Change /etc/nsswitch.conf file
    template: src=nsswitch.conf.j2 dest=/etc/nsswitch.conf owner=root mode=644
    when: ansible_distribution == 'FreeBSD'

  - name: Configure libnss-ldapd
    debconf: name=libnss-ldapd question='libnss-ldapd/nsswitch' value='group, hosts, passwd, shadow' vtype='multiselect'
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Update PAM Auth
    command: pam-auth-update
    environment:
    - DEBIAN_FRONTEND: noninteractive

  - name: Change /etc/pam.d/common-session file
    lineinfile: dest=/etc/pam.d/common-session insertbefore="# end of pam-auth-update config" line="session required pam_mkhomedir.so skel=/etc/skel/ umask=0077"
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
